### ISSUE TITLE
Predicates to compare to nil

### ISSUE THREAD

**Issue by victor** [QueryKit/QueryKit#43] opened 2015-10-20 15:55 UTC
When I try to create a filter that excludes or includes nil values, I'm getting an error message:

    queryset.filter{ $0.configuration == nil }

> Type of expresion is ambiguous without more context

If I try to create a predicate instead:

    let predicate = Widget.configuration == nil

> Value of type 'Attribute<Configuration>' can never be nil, comparison isn't allowed

What am I doing wrong?

**Comment by kylef** [comment] 2015-10-20 16:09
@victor Can you share how the attribute is defined for `configuration` inside `Widget`.

**Comment by victor** [comment] 2015-10-20 16:23
It is a relationship to another entity:

```
    @NSManaged public
    var configuration: Configuration?
```
and in the QueryKit extension:
```
  static var configuration:Attribute<Configuration> { return Attribute("configuration") }
```

**Comment by kylef** [comment] 2015-10-20 16:27
Thanks @victor, you clarify the following:

- `configuration` is optional (not required) in your Core Data model?
- You used [querykit-cli](https://github.com/QueryKit/QueryKit-cli) to generate these extensions?

**Comment by kylef** [comment] 2015-10-20 16:38
Hmm, looking at the code that shouldn't matter anyway. We allow optional right-hand-side regardless.

https://github.com/QueryKit/QueryKit/blob/master/QueryKit/Predicate.swift#L30

Looks like the equatable Swift rules are taking precedence over the custom operator in these cases.

Could you try the branch `attribute-equatable` and see if it solves your problem @victor.

**Comment by victor** [comment] 2015-10-20 17:06
I tried both making it optional and not (actually, I was interested in that query to help me debug a validation error). And yes, I used querykit-cli.
And, the same error message appears in `attribute-equatable`

**Comment by kylef** [comment] 2015-10-20 17:31
I've [added a test case](https://github.com/QueryKit/QueryKit/blob/master/QueryKitTests/QuerySetTests.swift#L108-L111) which demonstrates this works correctly from the type-safe filter on master.

![screen shot 2015-10-20 at 10 28 55](https://cloud.githubusercontent.com/assets/44164/10615555/64b1e3f6-7715-11e5-9b0c-54a361213e7d.png)

Are you able to reduce this down to a sample project you could share?

**Comment by victor** [comment] 2015-10-20 17:38
I'll see what I can do, Kile. Thanks for your help.

**Comment by kylef** [comment] 2015-11-06 16:43
Hi @victor, did you figure anything out regarding this issue? Is there anything I can help with?

**Comment by victor** [comment] 2015-11-18 08:43
Sorry, I haven't had time to reduce the test case. I implemented my query without QK so it was no longer urgent for me.

**Comment by kylef** [comment] 2016-02-28 17:44
Going to close this as I'm unable to reproduce.

If anyone has problems with this please mention and I'll be happy to re-open and investigate this problem further.

**Closed by kylef** 2016-02-28 17:44 UTC
